name: Add Reviewers

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REVIEWER_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['kat-kan', 'Justyna-KO', 'Slawomir-DKl']
            });
